---
title: "Introducción"
numbered: true
---

1. Problema de investigación
La confianza en las instituciones es un indicador crítico de la estabilidad democrática y la legitimidad de un régimen [@han_trust_2021; (OECD, 2024)]. En el Chile contemporáneo, este fenómeno ha adquiriere particular relevancia debido a la aparente erosión que ha situado a organismos como el Congreso Nacional y los partidos políticos con índices de confianza inferiores al 5% [@ministeriodedesarrollosocialyfamilia_informe_2020]. El problema central de este documento radica en explorar cómo las trayectorias de esta confianza se han visto afectadas por elementos como el timepo, la clase social, la coherte generacional, sentido de pertenencia y el percepción de corrupción.

2. Contexto teórico
La confianza institucional es uno de los principales elementos de la cohesión social vertical [@chan_charting_2006]. Schiefer y van der Noll [@_essentials_2017] la definen como un componente constitutivo de la convivencia que actúa como "pegamento social" al reducir los costos de gobernanza y fomentar la adscripción voluntaria a las normas [@ministeriodedesarrollosocialyfamilia_informe_2020; @kim_social_2021]. Sin embargo, la literatura advierte que este recurso se reconfigura dinámicamente: la clase social podría constituir un predictor de confianza particularmente relevante debido a que las distintas posiciones en el mercado laboral generan estándares de evaluación asimétricos respecto a la eficacia y probidad de las agencias estatales [@molina_repensando_2022]. A esta estratificación se suma el impacto del nivel educativo, entendido como una forma de capital cultural que, al acumularse, puede facilitar una mayor integración en las estructuras del Estado [@kim_social_2021]. No obstante, la relación es compleja; mientras que niveles de instrucción superiores como el posgrado actúan como habilitadores robustos de la confianza, la teoría sugiere que un mayor capital cognitivo también puede derivar en estándares de evaluación más exigentes y una postura más crítica frente al desempeño gubernamental.
Por otro lado, la cohorte generacional introduce una evidente erocion en la dimension vertical de la cohesión social: las generaciones más jóvenes, manifiestan progresivamente un distanciamiento significativo de las instituciones al haber abandonado los "surcos de legitimidad" tradicionales que guiaban a las generaciones precedentes [@diazsarmiento_entendiendo_2017; (@_confianza_2024D, 2024)].
En contraste, el sentido de pertenencia nacional funciona como el principal motor de resiliencia, operando como una "reserva cultural" o amortiguador que protege el vínculo sociedad-Estado incluso ante choques de deslegitimación profunda [(Castillo, Espinoza & Barozet, 2022)]. Para @_essentials_2017, este sentimiento de pertenencia es una dimensión constitutiva y esencial de la cohesión social, actuando como el cimiento emocional que permite la estabilidad democrática aun cuando la evaluación de las autoridades sea negativa [@_essentials_2017].[@ministeriodedesarrollosocialyfamilia_informe_2020]. Por ultimo, la literatura advierte que la demanda de equidad en el trato y el rechazo a asimetrías de poder son precondiciones para la legitimidad del sistema; por tanto, las experiencias de maltrato percibido vinculadas frecuentemente al clasismo tensionan el pacto social y profundizan la desafección vertical [(Araujo, 2013)].

3. Estrategia empírica
Para contrastar empiricamente las relaciones propuestas por la teoría, el estudio utiliza datos del Estudio Longitudinal Social de Chile (ELSOC) en el periodo 2016-2023. Se emplea una estrategia de modelación jerarquica (multinivel) que permite capturar simultáneamente la variabilidad entre individuos (between) y los cambios intra-individuales en el tiempo (within). Aprovechando la estructura panel de los datos, se agruparon las observaciones por individuo y siguiendo las recomendaciones de @enders_centering_2007, se procedió al centrado a la media de grupo (CWC) para los predictores de Nivel 1 y a la inclusión de promedios históricos en el Nivel 2 para garantizar la estimación pura de los efectos intra-sujeto y entre-sujetos.
4. Resumen de resultados
Los hallazgos demuestran que la percepción de corrupción es el principal detractor de la confianza; el impacto de la desconfianza crónica (promedio personal a lo largod el tiempo) es cuatro veces superior al del cambio a lo largo del tiempo. (β=−2.090 vs. β=−0.494). Por el contrario, la identificación nacional cuenta con un efecto positivo. Asimismo, se constata la fractura estructural mencionada: la clase trabajadora manual y la Generación Z exhiben un distanciamiento sistemático y significativo de las instituciones.
5. Alcances y límites del proyecto
Este estudio se inscribe en un marco de ciencia abierta, poniendo a disposición de la comunidad universitaria sus códigos, datos y textos en un repositorio público para su réplica y crítica. Entre sus alcances destaca la capacidad de modelar trayectorias de cambio real gracias a los dates de estructura panel y tratamiento adecuardo para analisis longitudinal. No obstante, el proyecto reconoce límites en el tratamiento de variables; que ante su ausencia debieron ser imputadas. Esta practica se traduce en la omision de fluctuaciones temporales en las variables que carecen de informacion en algun periodo. Además, dada la limitación de tiempo y capacidades, este diagnóstico no pretende dar una explicacion exhaustiva del fenomeno.