name: Actualizar Arbol de Carpetas

on:
  push:
    branches:
      - main  # Si tu rama principal se llama master, cambia esto por master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v4

    - name: Instalar tree y generar estructura
      run: |
        sudo apt-get install -y tree
        # Ignora carpetas basura de Quarto y librerías ocultas
        tree --charset=ascii -I '.git|.github|.Rproj.user|docs|site_libs|*_files|_freeze|*.html|tree.txt|search.json|includes|assets' > tree.txt

    - name: Inyectar en el README
      run: |
        {
          echo '```'
          cat tree.txt
          echo '```'
        } > tree_wrapped.txt
        sed -i '/<!--START_TREE-->/,/<!--END_TREE-->/{/<!--START_TREE-->/!{/<!--END_TREE-->/!d}}' README.md
        sed -i '/<!--START_TREE-->/r tree_wrapped.txt' README.md

    - name: Auto-commit y Push
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add README.md
        git diff-index --quiet HEAD || git commit -m "Bot: Estructura de carpetas actualizada"
        git push